version: "3.9"

services:

  eureka-server:
    build: ./eureka-server
    container_name: eureka-server
    ports:
      - "8761:8761"
    volumes:
      - ./eureka-server:/app
      - ~/.m2:/root/.m2
    environment:
      - SPRING_PROFILES_ACTIVE=dev

  auth-service:
    build: ./auth-service
    container_name: auth-service
    ports:
      - "8083:8083"
    depends_on:
      - eureka-server
    volumes:
      - ./auth-service:/app
      - ~/.m2:/root/.m2
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - EUREKA_URL=http://eureka-server:8761/eureka
      - DB_URL=jdbc:mysql://host.docker.internal:3306/cjs_db
      - DB_USERNAME=root
      - DB_PASSWORD=cdac

  problem-service:
    build: ./cjs-service
    container_name: cjs-service
    ports:
      - "8082:8082"
    depends_on:
      - eureka-server
    volumes:
      - ./cjs-service:/app
      - ~/.m2:/root/.m2
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - EUREKA_URL=http://eureka-server:8761/eureka
      - DB_URL=jdbc:mysql://host.docker.internal:3306/cjs_db
      - DB_USERNAME=root
      - DB_PASSWORD=cdac
      - DOCKER_HOST=tcp://host.docker.internal:2375
  
  mcq-service:
    build: ./mcq-service
    container_name: mcq-service
    ports:
      - "8085:8085"
    depends_on:
      - eureka-server
    volumes:
      - ./mcq-service:/app
      - ~/.m2:/root/.m2
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - EUREKA_URL=http://eureka-server:8761/eureka
      - DB_URL=jdbc:mysql://host.docker.internal:3306/cjs_db
      - DB_USERNAME=root
      - DB_PASSWORD=cdac

  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - "5046:5046"
    depends_on:
      - eureka-server
    volumes:
      - ./api-gateway:/app
      - ~/.m2:/root/.m2
    environment:
      - AUTH_SERVICE_HOST=auth-service
      - AUTH_SERVICE_PORT=8083

      - CJS_SERVICE_HOST=cjs-service
      - CJS_SERVICE_PORT=8082

      - MCQ_SERVICE_HOST=mcq-service
      - MCQ_SERVICE_PORT=8085

      - CORS_ALLOWED_ORIGIN=http://localhost:5173
      - EUREKA_URL=http://eureka-server:8761/eureka
